-- ============================================================================
-- 0004 — Reference data (controlled vocabularies)
--
-- WHY: the option lists that matching depends on (specialties, modalities,
-- age bands, ...) were baked into each client separately — and had ALREADY
-- drifted: the website portal offered 'Blue Cross Blue Shield' while the app
-- matches on 'BCBS', so a profile built on one surface partially failed to
-- match on the other. A typo-level difference silently breaks matching.
--
-- This makes the database the single source of truth. Clients fetch
-- get_vocab() at boot and fall back to their baked copies offline. Adding a
-- specialty becomes an INSERT — no app release, no website deploy.
--
-- Seeded programmatically from the app's lists on 2026-07-23 (the app is
-- canonical because the matching functions score against these exact strings).
-- ============================================================================

create table if not exists vocab (
  kind   text not null,   -- e.g. 'specialty_core', 'modality_more', 'age_band'
  value  text not null,
  sort   int  default 0,
  active boolean default true,
  primary key (kind, value)
);

alter table vocab enable row level security;

-- anyone may read active vocabulary; writes are service-role only (no policy)
create policy "read active vocab" on vocab
  for select to anon, authenticated using (active);

-- One call returns every list, keyed by kind, in display order.
create or replace function get_vocab()
returns jsonb
language sql
stable
set search_path = public
as $$
  select coalesce(jsonb_object_agg(kind, vals), '{}'::jsonb)
  from (
    select kind, jsonb_agg(value order by sort, value) as vals
    from vocab
    where active
    group by kind
  ) x;
$$;

grant execute on function get_vocab to anon, authenticated;

insert into vocab (kind, value, sort) values
  ('specialty_core', 'Anxiety', 0),
  ('specialty_core', 'Trauma', 1),
  ('specialty_core', 'Couples', 2),
  ('specialty_core', 'Grief', 3),
  ('specialty_core', 'Life Transitions', 4),
  ('specialty_core', 'Burnout', 5),
  ('specialty_core', 'ADHD', 6),
  ('specialty_core', 'Substance Use', 7),
  ('specialty_core', 'Postpartum', 8),
  ('specialty_core', 'Family Conflict', 9),
  ('specialty_more', 'Addiction', 0),
  ('specialty_more', 'Adoption', 1),
  ('specialty_more', 'Alcohol Use', 2),
  ('specialty_more', 'Anger Management', 3),
  ('specialty_more', 'Anorexia', 4),
  ('specialty_more', 'Antisocial Personality (ASPD)', 5),
  ('specialty_more', 'ARFID', 6),
  ('specialty_more', 'Autism', 7),
  ('specialty_more', 'Behavioral Issues', 8),
  ('specialty_more', 'Binge Eating Disorder', 9),
  ('specialty_more', 'Bipolar Disorder', 10),
  ('specialty_more', 'Blended Family', 11),
  ('specialty_more', 'Body Image', 12),
  ('specialty_more', 'Borderline Personality (BPD)', 13),
  ('specialty_more', 'Bulimia', 14),
  ('specialty_more', 'Cancer', 15),
  ('specialty_more', 'Career Counseling', 16),
  ('specialty_more', 'Child Anxiety', 17),
  ('specialty_more', 'Chronic Illness', 18),
  ('specialty_more', 'Chronic Pain', 19),
  ('specialty_more', 'Co-Parenting', 20),
  ('specialty_more', 'Codependency', 21),
  ('specialty_more', 'Complex PTSD', 22),
  ('specialty_more', 'Dementia', 23),
  ('specialty_more', 'Depersonalization (DPDR)', 24),
  ('specialty_more', 'Depression', 25),
  ('specialty_more', 'Dissociative Disorders (DID)', 26),
  ('specialty_more', 'Divorce', 27),
  ('specialty_more', 'Domestic Abuse', 28),
  ('specialty_more', 'Driving Anxiety', 29),
  ('specialty_more', 'Drug Abuse', 30),
  ('specialty_more', 'Dual Diagnosis', 31),
  ('specialty_more', 'Eating Disorders', 32),
  ('specialty_more', 'Education and Learning Disabilities', 33),
  ('specialty_more', 'Emotional Abuse', 34),
  ('specialty_more', 'Emotional Regulation', 35),
  ('specialty_more', 'First Responders', 36),
  ('specialty_more', 'Gambling', 37),
  ('specialty_more', 'Geriatric', 38),
  ('specialty_more', 'Health Anxiety', 39),
  ('specialty_more', 'Hoarding', 40),
  ('specialty_more', 'Infertility', 41),
  ('specialty_more', 'Infidelity', 42),
  ('specialty_more', 'Intellectual Disability', 43),
  ('specialty_more', 'Internet Addiction', 44),
  ('specialty_more', 'Life Coaching', 45),
  ('specialty_more', 'Marriage Counseling', 46),
  ('specialty_more', 'Medical Detox', 47),
  ('specialty_more', 'Medical Trauma', 48),
  ('specialty_more', 'Medication Management', 49),
  ('specialty_more', 'Men''s Issues', 50),
  ('specialty_more', 'Menopause', 51),
  ('specialty_more', 'Miscarriage', 52),
  ('specialty_more', 'Narcissistic Abuse', 53),
  ('specialty_more', 'Narcissistic Personality (NPD)', 54),
  ('specialty_more', 'Neurodivergence', 55),
  ('specialty_more', 'Obesity', 56),
  ('specialty_more', 'Obsessive-Compulsive (OCD)', 57),
  ('specialty_more', 'Oppositional Defiance (ODD)', 58),
  ('specialty_more', 'Parenting', 59),
  ('specialty_more', 'Personality Disorders', 60),
  ('specialty_more', 'Porn Addiction', 61),
  ('specialty_more', 'Postpartum Depression', 62),
  ('specialty_more', 'Pregnancy, Prenatal, Postpartum', 63),
  ('specialty_more', 'Premarital', 64),
  ('specialty_more', 'Premenstrual Dysphoric Disorder (PMDD)', 65),
  ('specialty_more', 'Psychosis', 66),
  ('specialty_more', 'Racial Identity', 67),
  ('specialty_more', 'Relationship Anxiety', 68),
  ('specialty_more', 'Relationship Issues', 69),
  ('specialty_more', 'Schizophrenia', 70),
  ('specialty_more', 'Self Esteem', 71),
  ('specialty_more', 'Self-Harming', 72),
  ('specialty_more', 'Sex Therapy', 73),
  ('specialty_more', 'Sexual Abuse', 74),
  ('specialty_more', 'Sexual Addiction', 75),
  ('specialty_more', 'Sleep or Insomnia', 76),
  ('specialty_more', 'Social Anxiety', 77),
  ('specialty_more', 'Spirituality', 78),
  ('specialty_more', 'Sports Performance', 79),
  ('specialty_more', 'Stress', 80),
  ('specialty_more', 'Suicidal Ideation', 81),
  ('specialty_more', 'Testing and Evaluation', 82),
  ('specialty_more', 'Trauma and PTSD', 83),
  ('specialty_more', 'Traumatic Brain Injury (TBI)', 84),
  ('specialty_more', 'Veterans', 85),
  ('specialty_more', 'Video Game Addiction', 86),
  ('specialty_more', 'Weight Loss', 87),
  ('specialty_more', 'Women''s Issues', 88),
  ('modality_core', 'CBT', 0),
  ('modality_core', 'EMDR', 1),
  ('modality_core', 'ACT', 2),
  ('modality_core', 'EFT', 3),
  ('modality_core', 'Motivational Interviewing', 4),
  ('modality_quick', 'ERP', 0),
  ('modality_quick', 'ACT', 1),
  ('modality_quick', 'Motivational Interviewing', 2),
  ('modality_quick', 'Somatic', 3),
  ('modality_quick', 'EMDR', 4),
  ('modality_quick', 'IFS', 5),
  ('modality_quick', 'DBT', 6),
  ('modality_quick', 'Couples Therapy', 7),
  ('modality_more', 'Adlerian', 0),
  ('modality_more', 'AEDP', 1),
  ('modality_more', 'Applied Behavioral Analysis (ABA)', 2),
  ('modality_more', 'Art Therapy', 3),
  ('modality_more', 'Attachment-based', 4),
  ('modality_more', 'Biofeedback', 5),
  ('modality_more', 'Brainspotting', 6),
  ('modality_more', 'Clinical Supervision and Licensed Supervisors', 7),
  ('modality_more', 'Coaching', 8),
  ('modality_more', 'Cognitive Behavioral (CBT)', 9),
  ('modality_more', 'Cognitive Processing (CPT)', 10),
  ('modality_more', 'Compassion Focused', 11),
  ('modality_more', 'Culturally Sensitive', 12),
  ('modality_more', 'Dance Movement Therapy', 13),
  ('modality_more', 'Eclectic', 14),
  ('modality_more', 'Emotionally Focused', 15),
  ('modality_more', 'Energy Psychology', 16),
  ('modality_more', 'Existential', 17),
  ('modality_more', 'Experiential Therapy', 18),
  ('modality_more', 'Expressive Arts', 19),
  ('modality_more', 'Family Systems', 20),
  ('modality_more', 'Family Therapy', 21),
  ('modality_more', 'Feminist', 22),
  ('modality_more', 'Forensic Psychology', 23),
  ('modality_more', 'Gestalt', 24),
  ('modality_more', 'Gottman Method', 25),
  ('modality_more', 'Humanistic', 26),
  ('modality_more', 'Hypnotherapy', 27),
  ('modality_more', 'Imago', 28),
  ('modality_more', 'Integrative', 29),
  ('modality_more', 'Interpersonal', 30),
  ('modality_more', 'Intervention', 31),
  ('modality_more', 'Jungian', 32),
  ('modality_more', 'Ketamine-Assisted', 33),
  ('modality_more', 'Mindfulness-Based (MBCT)', 34),
  ('modality_more', 'Multicultural', 35),
  ('modality_more', 'Music Therapy', 36),
  ('modality_more', 'Narrative', 37),
  ('modality_more', 'Neuro-Linguistic (NLP)', 38),
  ('modality_more', 'Neurofeedback', 39),
  ('modality_more', 'Parent-Child Interaction (PCIT)', 40),
  ('modality_more', 'Person-Centered', 41),
  ('modality_more', 'Play Therapy', 42),
  ('modality_more', 'Positive Psychology', 43),
  ('modality_more', 'Prolonged Exposure Therapy', 44),
  ('modality_more', 'Psychoanalytic', 45),
  ('modality_more', 'Psychobiological Approach Couple Therapy', 46),
  ('modality_more', 'Psychodynamic', 47),
  ('modality_more', 'Rational Emotive Behavior (REBT)', 48),
  ('modality_more', 'Reality Therapy', 49),
  ('modality_more', 'Relational', 50),
  ('modality_more', 'Sandplay', 51),
  ('modality_more', 'Schema Therapy', 52),
  ('modality_more', 'Solution Focused Brief (SFBT)', 53),
  ('modality_more', 'Strength-Based', 54),
  ('modality_more', 'Structural Family Therapy', 55),
  ('modality_more', 'Transpersonal', 56),
  ('modality_more', 'Trauma Focused', 57),
  ('insurance_core', 'Aetna', 0),
  ('insurance_core', 'BCBS', 1),
  ('insurance_core', 'Cigna', 2),
  ('insurance_core', 'United', 3),
  ('insurance_core', 'EAP', 4),
  ('insurance_more', '1199SEIU', 0),
  ('insurance_more', 'AARP', 1),
  ('insurance_more', 'ACI Specialty Benefits', 2),
  ('insurance_more', 'Aetna EAP', 3),
  ('insurance_more', 'Aetna Medicare', 4),
  ('insurance_more', 'Aetna Student Health', 5),
  ('insurance_more', 'All Savers', 6),
  ('insurance_more', 'AllOne Health', 7),
  ('insurance_more', 'America''s Choice Provider Network (ACPN)', 8),
  ('insurance_more', 'AmeriHealth Caritas', 9),
  ('insurance_more', 'Anthem', 10),
  ('insurance_more', 'Anthem EAP', 11),
  ('insurance_more', 'APS Healthcare', 12),
  ('insurance_more', 'Ascension SmartHealth', 13),
  ('insurance_more', 'BHS | Behavioral Health Systems', 14),
  ('insurance_more', 'Blue Cross', 15),
  ('insurance_more', 'Blue Shield', 16),
  ('insurance_more', 'BlueCross BlueShield', 17),
  ('insurance_more', 'Carebridge EAP', 18),
  ('insurance_more', 'CareConnect Health Plan', 19),
  ('insurance_more', 'Carelon Behavioral Health', 20),
  ('insurance_more', 'CareOregon', 21),
  ('insurance_more', 'CCN | Community Care Network', 22),
  ('insurance_more', 'Centivo', 23),
  ('insurance_more', 'CHAMPVA', 24),
  ('insurance_more', 'Children''s Health Insurance Program (CHIP)', 25),
  ('insurance_more', 'ChoiceCare Network', 26),
  ('insurance_more', 'Cigna and Evernorth', 27),
  ('insurance_more', 'Cigna EAP', 28),
  ('insurance_more', 'Cigna Medicare', 29),
  ('insurance_more', 'Cofinity | First Health', 30),
  ('insurance_more', 'Colorado Access', 31),
  ('insurance_more', 'ComPsych', 32),
  ('insurance_more', 'Concern', 33),
  ('insurance_more', 'Coventry', 34),
  ('insurance_more', 'CuraLinc Healthcare', 35),
  ('insurance_more', 'Curative', 36),
  ('insurance_more', 'Dayforce', 37),
  ('insurance_more', 'Denver Health Medical Plan', 38),
  ('insurance_more', 'ESI Employee Assistance Group', 39),
  ('insurance_more', 'Evernorth EAP', 40),
  ('insurance_more', 'First Health', 41),
  ('insurance_more', 'Friday Health Plans', 42),
  ('insurance_more', 'Golden Rule', 43),
  ('insurance_more', 'Government Employees Health Association (GEHA)', 44),
  ('insurance_more', 'Great-West Life', 45),
  ('insurance_more', 'Guardian', 46),
  ('insurance_more', 'Health First Colorado', 47),
  ('insurance_more', 'Health Net', 48),
  ('insurance_more', 'Horizon Healthcare', 49),
  ('insurance_more', 'Humana', 50),
  ('insurance_more', 'Humana Dual', 51),
  ('insurance_more', 'Humana Medicare', 52),
  ('insurance_more', 'Independence Administrators', 53),
  ('insurance_more', 'Kaiser Permanente (OON)', 54),
  ('insurance_more', 'Lyra Health', 55),
  ('insurance_more', 'Magellan', 56),
  ('insurance_more', 'MagnaCare', 57),
  ('insurance_more', 'Managed Health Network (MHN)', 58),
  ('insurance_more', 'Medicaid', 59),
  ('insurance_more', 'Medicare', 60),
  ('insurance_more', 'MediNcrease Health Plans (MHP)', 61),
  ('insurance_more', 'Meritain Health', 62),
  ('insurance_more', 'Military OneSource', 63),
  ('insurance_more', 'MINES and Associates', 64),
  ('insurance_more', 'Modern Health', 65),
  ('insurance_more', 'Molina Healthcare', 66),
  ('insurance_more', 'MotivHealth', 67),
  ('insurance_more', 'MultiPlan', 68),
  ('insurance_more', 'MultiPlan Private Healthcare Systems (PHCS)', 69),
  ('insurance_more', 'Mutual of Omaha', 70),
  ('insurance_more', 'New Directions | Lucet', 71),
  ('insurance_more', 'Nippon Life Benefits', 72),
  ('insurance_more', 'Northwell Direct', 73),
  ('insurance_more', 'Optum', 74),
  ('insurance_more', 'Oscar Health', 75),
  ('insurance_more', 'Oxford', 76),
  ('insurance_more', 'Partners Direct Health', 77),
  ('insurance_more', 'Provider Network of America (PNOA)', 78),
  ('insurance_more', 'PsychCare', 79),
  ('insurance_more', 'Reliant', 80),
  ('insurance_more', 'Rocky Mountain Health Plans', 81),
  ('insurance_more', 'Sagamore', 82),
  ('insurance_more', 'Sana Benefits', 83),
  ('insurance_more', 'SelectHealth', 84),
  ('insurance_more', 'Surest', 85),
  ('insurance_more', 'TELUS Health', 86),
  ('insurance_more', 'TRICARE', 87),
  ('insurance_more', 'TriWest', 88),
  ('insurance_more', 'Trustmark Benefits', 89),
  ('insurance_more', 'Ulliance', 90),
  ('insurance_more', 'United Medical Resources (UMR)', 91),
  ('insurance_more', 'UnitedHealthcare / Optum EAP', 92),
  ('insurance_more', 'UnitedHealthcare / Optum Medicaid', 93),
  ('insurance_more', 'UnitedHealthcare / Optum Medicare', 94),
  ('insurance_more', 'UnitedHealthcare Student Resources', 95),
  ('insurance_more', 'UnitedHealthcare UHC | UBH', 96),
  ('insurance_more', 'VA Community Care Network (CCN)', 97),
  ('insurance_more', 'Velocity National Provider Network (VNPN)', 98),
  ('insurance_more', 'WellCare', 99),
  ('insurance_more', 'Wellfleet', 100),
  ('insurance_more', 'Wellpoint | Amerigroup', 101),
  ('insurance_more', 'Workplace Options', 102),
  ('insurance_more', 'Zelis Healthcare', 103),
  ('language_quick', 'English', 0),
  ('language_quick', 'Spanish', 1),
  ('language_quick', 'Mandarin', 2),
  ('language_more', 'American Sign Language', 0),
  ('language_more', 'Arabic', 1),
  ('language_more', 'Bengali', 2),
  ('language_more', 'Burmese', 3),
  ('language_more', 'Cantonese', 4),
  ('language_more', 'Czech', 5),
  ('language_more', 'Dutch', 6),
  ('language_more', 'French', 7),
  ('language_more', 'German', 8),
  ('language_more', 'Greek', 9),
  ('language_more', 'Haitian Creole', 10),
  ('language_more', 'Hausa', 11),
  ('language_more', 'Hebrew', 12),
  ('language_more', 'Hindi', 13),
  ('language_more', 'Hmong', 14),
  ('language_more', 'Hungarian', 15),
  ('language_more', 'Igbo', 16),
  ('language_more', 'Indonesian', 17),
  ('language_more', 'Italian', 18),
  ('language_more', 'Japanese', 19),
  ('language_more', 'Khmer', 20),
  ('language_more', 'Korean', 21),
  ('language_more', 'Lao', 22),
  ('language_more', 'Nepali', 23),
  ('language_more', 'Persian (Farsi)', 24),
  ('language_more', 'Polish', 25),
  ('language_more', 'Portuguese', 26),
  ('language_more', 'Punjabi', 27),
  ('language_more', 'Romanian', 28),
  ('language_more', 'Russian', 29),
  ('language_more', 'Serbian', 30),
  ('language_more', 'Sinhala', 31),
  ('language_more', 'Somali', 32),
  ('language_more', 'Swahili', 33),
  ('language_more', 'Swedish', 34),
  ('language_more', 'Tagalog', 35),
  ('language_more', 'Thai', 36),
  ('language_more', 'Turkish', 37),
  ('language_more', 'Ukrainian', 38),
  ('language_more', 'Urdu', 39),
  ('language_more', 'Vietnamese', 40),
  ('language_more', 'Yoruba', 41),
  ('age_band', '18–24', 0),
  ('age_band', '25–34', 1),
  ('age_band', '35–44', 2),
  ('age_band', '45–54', 3),
  ('age_band', '55–64', 4),
  ('age_band', '65+', 5),
  ('client_gender', 'Female', 0),
  ('client_gender', 'Male', 1),
  ('client_gender', 'Non-binary', 2),
  ('client_gender', 'Transgender', 3),
  ('client_gender', 'Prefer not to say', 4),
  ('client_field', 'First responder', 0),
  ('client_field', 'Healthcare', 1),
  ('client_field', 'Military & Veteran', 2),
  ('client_field', 'Education', 3),
  ('client_field', 'Tech', 4),
  ('client_field', 'Finance & Legal', 5),
  ('client_field', 'Service industry', 6),
  ('client_field', 'Student', 7),
  ('client_field', 'Full-time parent', 8),
  ('client_field', 'Creative', 9),
  ('client_field', 'Other', 10),
  ('prev_experience', 'More direct feedback', 0),
  ('prev_experience', 'More structure and homework', 1),
  ('prev_experience', 'Less structure, more space to talk', 2),
  ('prev_experience', 'Someone who challenges me', 3),
  ('prev_experience', 'Someone gentler', 4),
  ('prev_experience', 'A different approach entirely', 5),
  ('prev_experience', 'Someone who shares my identity', 6),
  ('prev_experience', 'Better at handling trauma', 7),
  ('prev_experience', 'Nothing — it worked, I moved', 8)
on conflict (kind, value) do nothing;
